import requests

parameters = {
    'amount' : 15,
    'type' : 'boolean'
}
response = requests.get("https://opentdb.com/api.php",params=parameters)
response.raise_for_status()
#print(response.json()["results"])
question_data = response.json()["results"]




# question_data = [
#     {"text": "A slug's blood is green.", "answer": "True"},
#     {"text": "The loudest animal is the African Elephant.", "answer": "False"},
#     {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
#     {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
#     {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
#     {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
#     {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
#     {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
#     {"text": "Google was originally called 'Backrub'.", "answer": "True"},
#     {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
#     {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
#     {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
# ]

# question_data = [
#                      {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
#                       "question": "Amazon acquired Twitch in August 2014 for $970 million dollars.",
#                       "correct_answer": "True",
#                       "incorrect_answers": ["False"]},
#                      {"category": "Mythology", "type": "boolean", "difficulty": "easy",
#                       "question": "In Norse mythology, Thor once dressed as a woman.",
#                       "correct_answer": "True", "incorrect_answers": ["False"]},
#                      {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
#                       "question": "The Great Wall of China is visible from the moon.", "correct_answer": "False",
#                       "incorrect_answers": ["True"]},
#                      {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
#                       "question": "The US emergency hotline is 911 because of the September 11th terrorist attacks.",
#                       "correct_answer": "False", "incorrect_answers": ["True"]},
#                      {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
#                       "question": "French is an official language in Canada.", "correct_answer": "True",
#                       "incorrect_answers": ["False"]},
#                      {"category": "Animals", "type": "boolean",
#                       "difficulty": "easy",
#                       "question": "Kangaroos keep food in their pouches next to their children.",
#                       "correct_answer": "False",
#                       "incorrect_answers": ["True"]},
#                      {"category": "Geography",
#                       "type": "boolean",
#                       "difficulty": "easy",
#                       "question": "There is a city called Rome in every continent on Earth.",
#                       "correct_answer": "False",
#                       "incorrect_answers": ["True"]},
#                      {"category": "Geography",
#                       "type": "boolean",
#                       "difficulty": "easy",
#                       "question": "Alaska is the largest state in the United States.",
#                       "correct_answer": "True",
#                       "incorrect_answers": ["False"]},
#                      {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
#                       "question": "The first &quot;Metal Gear&quot; game was released for the PlayStation 1.",
#                       "correct_answer": "False",
#                       "incorrect_answers": ["True"]}, {"category": "Animals", "type": "boolean", "difficulty": "easy",
#                                                        "question": "A bear does NOT defecate during hibernation. ",
#                                                        "correct_answer": "True", "incorrect_answers": ["False"]},
#                      {"category": "Science: Gadgets", "type": "boolean", "difficulty": "easy",
#                       "question": "The communication protocol NFC stands for Near-Field Control.",
#                       "correct_answer": "False",
#                       "incorrect_answers": ["True"]}, {"category": "Sports", "type": "boolean", "difficulty": "medium",
#                                                        "question": "Tennis was once known as Racquetball.",
#                                                        "correct_answer": "False",
#                                                        "incorrect_answers": ["True"]},
#                      {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
#                       "question": "An atom contains a nucleus.",
#                       "correct_answer": "True", "incorrect_answers": ["False"]},
#                      {"category": "Mythology", "type": "boolean", "difficulty": "medium",
#                       "question": "According to Norse mythology, Loki is a mother.", "correct_answer": "True",
#                       "incorrect_answers": ["False"]},
#                      {"category": "Mythology", "type": "boolean", "difficulty": "medium",
#                       "question": "The Japanese god Izanagi successfully returned his wife Izanami from the Underworld.",
#                       "correct_answer": "False", "incorrect_answers": ["True"]},
#                      {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
#                       "question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
#                       "correct_answer": "True", "incorrect_answers": ["False"]},
#                      {"category": "Geography", "type": "boolean", "difficulty": "medium",
#                       "question": "&quot;Mongolia&quot; was a part of the now non-existent U.S.S.R.",
#                       "correct_answer": "False",
#                       "incorrect_answers": ["True"]},
#                      {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
#                       "question": "There is a Donald Trump Board Game, which was made in 1989.",
#                       "correct_answer": "True", "incorrect_answers": ["False"]},
#                      {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
#                       "question": "&quot;HTML&quot; stands for Hypertext Markup Language.", "correct_answer": "True",
#                       "incorrect_answers": ["False"]},
#                      {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
#                       "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
#                       "correct_answer": "False", "incorrect_answers": ["True"]},
#                      {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
#                       "question": "The first dual-core CPU was the Intel Pentium D.", "correct_answer": "False",
#                       "incorrect_answers": ["True"]},
#                      {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
#                       "question": "Mortal Kombat was almost based on Jean-Claude Van Damme movie.",
#                       "correct_answer": "True",
#                       "incorrect_answers": ["False"]},
#                      {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
#                       "question": "All of these maps were in &quot;Tom Clancy&#039;s Rainbow Six Siege&quot; on its initial release: House, Clubhouse, Border, Consulate.",
#                       "correct_answer": "False", "incorrect_answers": ["True"]},
#                      {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "hard",
#                       "question": "The board game Go has more possible legal positions than the number of atoms in the visible universe.",
#                       "correct_answer": "True", "incorrect_answers": ["False"]},
#                      {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
#                       "question": "In Portal, the Companion Cube&#039;s ARE sentient.", "correct_answer": "True",
#                       "incorrect_answers": ["False"]}, {"category": "Art", "type": "boolean", "difficulty": "easy",
#                                                         "question": "Leonardo da Vinci was not the creator of the Mona Lisa.",
#                                                         "correct_answer": "False", "incorrect_answers": ["True"]},
#                      {"category": "Sports", "type": "boolean", "difficulty": "medium",
#                       "question": "In 2008, Usain Bolt set the world record for the 100 meters with one shoelace untied.",
#                       "correct_answer": "True", "incorrect_answers": ["False"]},
#                      {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
#                       "question": "During pre-production of &quot;Super Mario Bros.&quot;, Mario originally was meant to shoot bullets.",
#                       "correct_answer": "True", "incorrect_answers": ["False"]},
#                      {"category": "History", "type": "boolean", "difficulty": "hard",
#                       "question": "The man that shot Alexander Hamilton was named Aaron Burr.",
#                       "correct_answer": "True",
#                       "incorrect_answers": ["False"]},
#                      {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
#                       "question": "The Paradox Interactive game &quot;Stellaris&quot; was released in 2016.",
#                       "correct_answer": "True",
#                       "incorrect_answers": ["False"]}]
